---
- name: Deploy web app
  hosts: all # имя хоста, который мы создадим Vagrant`om
  become: yes # Установка Docker через sudo
  gather_facts: false
  tasks: # Перечисляем задачи которые выполнит наш playbook

    - name: Install epel-release # устанавливаем пакеты необходимые для установки докера
      become: yes
      yum:
        name: epel-release
        state: present
      tags:
        - soft

    - name: Install ipaservers
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - ipa-server
        - ipa-server-dns
      tags:
        - soft
  
    - name: Configure freeipa
      command: |
        ipa-server-install -U \
        -r otus.com \
        -n otus.com \
        -p admin1 \
        -a admin1 \
        --hostname=ipaserver.otus.local \
        --ip-address=10.0.2.15 \
        --mkhomedir \
        --setup-dns \

